#!/usr/bin/env groovy

def label = "healthcare-${UUID.randomUUID().toString()}"
podTemplate(label: label, yaml: """
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
    - name: jdk
      image: openjdk:8-jdk
      command:
      - cat
      tty: true
"""
) {
    properties([
      buildDiscarder(logRotator(numToKeepStr: '5')),
      pipelineTriggers([snapshotDependencies()])])
    node (label) {
      checkout scm
      stage('Build') {
        container ('jdk') {
          def buildParameters = readYaml(file: 'build.yaml')
          withMaven(mavenOpts: '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn') {
            def goals = (env.BRANCH_NAME == 'master' || env.BRANCH_NAME =~ /v\d+\.x/ ) ? 'clean deploy' : 'clean verify'
            sh "./mvnw $goals"
          }
          mail to: "${buildParameters.notification.email}",
            subject: "${env.BUILD_DISPLAY_NAME} successful",
            body: "Please go to ${env.BUILD_URL} and verify the build"
          echo "Email sent to ${buildParameters.notification.email} defined in build.yaml"    
        }
      } // stage
    } // node
  }